# =============================================================================
# Team sport review - Figures 2-7
# Figs 2 and 4 are stacked bar charts; Figs 3, 5, 6 and 7 are UpSet plots.
# Fig 1 (PRISMA flow diagram) is not generated by this script.
# Built with ggplot2 + patchwork (no UpSetR / ComplexUpset dependency)
#
# Layout of each UpSet figure (standard UpSet):
#   top right    intersection bars, stacked by the grouping variable
#   bottom left  set-size bars  = COUNT OF EACH FIELD (with n printed)
#   bottom right dot matrix, rows = fields, columns = intersections
# =============================================================================

library(readxl)
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(patchwork)
library(viridisLite)   # `viridis` works too; viridisLite is the colour engine

data_path <- "Team_sport_review_extraction_final.xlsx"
out_dir   <- "figures"
dir.create(out_dir, showWarnings = FALSE)

# ---- 1. read + light tidying -------------------------------------------------

raw <- read_excel(data_path, sheet = "Data Extraction") |>
  mutate(study_id = row_number())

dat <- raw |>
  mutate(
    # "Team performance" is relabelled "Collective behaviour" throughout
    Area = factor(ifelse(Area == "Team performance", "Collective behaviour", Area),
                  levels = c("Sport specific skill", "Collective behaviour")),
    # Collapse the "7 different skills" / "13 different GK skills" style entries.
    # Set collapse_multi_skill <- FALSE to keep them as separate sets.
    `Sport Specific Skill` = if (TRUE) {
      str_replace(`Sport Specific Skill`,
                  regex("^(\\d+ different (GK )?skills|Multiple technical skills)$",
                        ignore_case = TRUE),
                  "Multiple skills")
    } else `Sport Specific Skill`
  )

# ---- 2. colours --------------------------------------------------------------

# Viridis purple + green for the two-level Study Area fill
area_cols <- c("Sport specific skill"  = "#440154",  # viridis purple
               "Collective behaviour" = "#35B779")  # viridis green

# option: "D" viridis, "A" magma, "B" inferno, "C" plasma, "E" cividis,
#         "F" rocket, "G" mako, "H" turbo
pal_for <- function(levels_vec, option = "D", begin = NULL, end = NULL) {
  if (all(levels_vec %in% names(area_cols)) && option == "D") {
    area_cols[levels_vec]
  } else {
    # magma/inferno/plasma/rocket/mako run from near-black to
    # near-white, so trim the extremes to keep every level legible
    warm  <- option %in% c("A", "B", "C", "F", "G")
    begin <- begin %||% if (warm) 0.20 else 0
    end   <- end   %||% if (warm) 0.80 else 0.92
    setNames(viridisLite::viridis(length(levels_vec), option = option,
                                  begin = begin, end = end),
             levels_vec)
  }
}
`%||%` <- function(x, y) if (is.null(x)) y else x

# integer-only axis breaks
int_breaks <- function(n = 5) function(x) {
  b <- pretty(c(0, max(x, na.rm = TRUE)), n = n)
  unique(b[b == floor(b)])
}

# ---- 3. the UpSet builder ----------------------------------------------------

make_upset <- function(data,
                       set_col,                 # column holding the (possibly
                                                #   comma-separated) fields
                       fill_col,                # grouping / stacking variable
                       set_axis_title  = set_col,
                       fill_title      = fill_col,
                       bar_axis_title  = "Studies (n)",
                       drop_values     = c("Not applicable", "NA", ""),
                       palette         = "D",   # see pal_for() for options
                       pal_begin       = NULL,
                       pal_end         = NULL,
                       min_intersection = 1,
                       max_intersections = Inf,
                       dot_size        = 3.1,
                       base_size       = 11,
                       widths          = c(1, 3.2),
                       heights         = c(2.2, 1.5)) {

  # --- long format: one row per study x field -------------------------------
  long <- data |>
    select(study_id, .set = all_of(set_col), .fill = all_of(fill_col)) |>
    mutate(.set  = as.character(.set),
           .fill = str_replace_all(str_squish(as.character(.fill)), ",\\s*", " + ")) |>
    filter(!is.na(.set)) |>
    separate_longer_delim(.set, delim = ",") |>
    mutate(.set = str_squish(.set)) |>
    filter(!.set %in% drop_values, !is.na(.fill)) |>
    distinct()

  if (nrow(long) == 0) stop("No rows left after filtering ", set_col)

  # --- ordering ------------------------------------------------------------
  set_order <- long |>                       # fields, most common first
    count(.set, sort = TRUE, name = "n") |>
    pull(.set)

  fill_levels <- if (is.factor(data[[fill_col]])) {
    intersect(levels(data[[fill_col]]), unique(long$.fill))
  } else {
    unique(long$.fill)[order(str_count(unique(long$.fill), fixed("+")),
                             unique(long$.fill))]
  }
  cols     <- pal_for(fill_levels, palette, pal_begin, pal_end)
  show_leg <- length(fill_levels) > 1   # a one-level legend says nothing

  # --- one intersection key per study ---------------------------------------
  keys <- long |>
    mutate(.set = factor(.set, levels = set_order)) |>
    arrange(study_id, .set) |>
    group_by(study_id, .fill) |>
    summarise(key    = paste(.set, collapse = " | "),
              degree = n(), .groups = "drop")

  totals <- keys |>
    count(key, degree, name = "n_total") |>
    filter(n_total >= min_intersection) |>
    arrange(desc(n_total), degree, key) |>
    filter(row_number() <= max_intersections)

  key_levels <- totals$key

  if (max(totals$degree) == 1)
    message("Note: '", set_col, "' has no multi-membership studies, so the ",
            "matrix is a diagonal and the UpSet reduces to a stacked bar ",
            "chart. See make_stacked_bar() for a simpler alternative.")

  bars <- keys |>
    filter(key %in% key_levels) |>
    count(key, .fill, name = "n") |>
    mutate(key   = factor(key, levels = key_levels),
           .fill = factor(.fill, levels = fill_levels))

  # --- matrix --------------------------------------------------------------
  members <- tibble(key = key_levels, .set = key_levels) |>
    separate_longer_delim(.set, delim = " | ") |>
    mutate(member = TRUE)

  grid <- expand_grid(key = key_levels, .set = set_order) |>
    left_join(members, by = c("key", ".set")) |>
    mutate(member = !is.na(member),
           key    = factor(key, levels = key_levels),
           .set   = factor(.set, levels = rev(set_order)))  # biggest at top

  segs <- grid |>
    filter(member) |>
    group_by(key) |>
    summarise(lo = min(as.integer(.set)), hi = max(as.integer(.set)),
              .groups = "drop")

  set_sizes <- long |>
    count(.set, .fill, name = "n") |>
    mutate(.set  = factor(.set, levels = rev(set_order)),
           .fill = factor(.fill, levels = fill_levels))

  set_totals <- set_sizes |>
    group_by(.set) |>
    summarise(n = sum(n), .groups = "drop")

  # --- theme ---------------------------------------------------------------
  base_theme <- theme_minimal(base_size = base_size) +
    theme(panel.grid.minor = element_blank(),
          plot.margin      = margin(2, 2, 2, 2),
          text             = element_text(colour = "grey15"))

  # --- top: intersection sizes ---------------------------------------------
  p_bar <- ggplot(bars, aes(key, n, fill = .fill)) +
    geom_col(width = 0.72, show.legend = show_leg) +
    geom_text(data = totals |> mutate(key = factor(key, levels = key_levels)),
              aes(key, n_total, label = n_total), inherit.aes = FALSE,
              vjust = -0.45, size = base_size / 3.4, colour = "grey25") +
    scale_fill_manual(values = cols, name = fill_title, drop = FALSE) +
    scale_y_continuous(breaks = int_breaks(5),
                       expand = expansion(mult = c(0, 0.12))) +
    scale_x_discrete(limits = key_levels, expand = expansion(add = 0.6)) +
    labs(y = bar_axis_title) +
    base_theme +
    theme(axis.title.x    = element_blank(),
          axis.text.x     = element_blank(),
          panel.grid.major.x = element_blank(),
          legend.position = "right")

  # --- bottom right: dot matrix --------------------------------------------
  p_mat <- ggplot() +
    geom_tile(data = tibble(.set = factor(rev(set_order), levels = rev(set_order))) |>
                mutate(stripe = as.integer(.set) %% 2 == 0) |> filter(stripe),
              aes(x = 1, y = .set), width = Inf, height = 0.9,
              fill = "grey95") +
    geom_point(data = grid, aes(key, .set),
               colour = "grey85", size = dot_size) +
    geom_segment(data = segs, aes(x = key, xend = key, y = lo, yend = hi),
                 colour = "grey20", linewidth = 0.6) +
    geom_point(data = filter(grid, member), aes(key, .set),
               colour = "grey15", size = dot_size) +
    scale_x_discrete(limits = key_levels, expand = expansion(add = 0.6)) +
    scale_y_discrete(limits = rev(set_order), expand = expansion(add = 0.5)) +
    labs(x = set_axis_title) +
    base_theme +
    theme(axis.title.y    = element_blank(),
          axis.text.x     = element_blank(),
          panel.grid      = element_blank(),
          axis.text.y     = element_text(hjust = 1, colour = "grey15"))

  # --- bottom left: set sizes (count of each field) -------------------------
  p_sets <- ggplot(set_sizes, aes(n, .set, fill = .fill)) +
    geom_col(width = 0.72, show.legend = FALSE) +
    geom_text(data = set_totals, aes(n, .set, label = n), inherit.aes = FALSE,
              hjust = 1.3, size = base_size / 3.4, colour = "grey25") +
    scale_fill_manual(values = cols, drop = FALSE) +
    scale_x_reverse(breaks = int_breaks(3),
                    expand = expansion(mult = c(0.22, 0))) +
    scale_y_discrete(limits = rev(set_order), expand = expansion(add = 0.5)) +
    labs(x = bar_axis_title) +
    base_theme +
    theme(axis.title.y       = element_blank(),
          axis.text.y        = element_blank(),
          panel.grid.major.y = element_blank())

  # --- assemble -------------------------------------------------------------
  (plot_spacer() + p_bar + p_sets + p_mat) +
    plot_layout(ncol = 2, widths = widths, heights = heights,
                guides = "collect") &
    theme(legend.position = if (show_leg) "right" else "none",
          legend.key.size = unit(0.85, "lines"))
}

# ---- 4. simpler alternative for single-membership variables -----------------
# Sport and Sport-specific skill are recorded one-per-study, so their UpSet
# matrices are diagonals. This gives the equivalent stacked bar chart.

make_stacked_bar <- function(data, set_col, fill_col,
                             set_axis_title = set_col,
                             fill_title     = fill_col,
                             bar_axis_title = "Studies (n)",
                             drop_values    = c("Not applicable", "NA", ""),
                             palette        = "D",
                             base_size      = 11) {

  long <- data |>
    select(study_id, .set = all_of(set_col), .fill = all_of(fill_col)) |>
    mutate(.set  = as.character(.set),
           .fill = str_replace_all(str_squish(as.character(.fill)), ",\\s*", " + ")) |>
    separate_longer_delim(.set, delim = ",") |>
    mutate(.set = str_squish(.set)) |>
    filter(!.set %in% drop_values, !is.na(.fill)) |>
    distinct()

  set_order   <- long |> count(.set, sort = TRUE) |> pull(.set)
  fill_levels <- if (is.factor(data[[fill_col]]))
    intersect(levels(data[[fill_col]]), unique(long$.fill)) else sort(unique(long$.fill))

  plot_dat <- long |>
    count(.set, .fill, name = "n") |>
    mutate(.set  = factor(.set, levels = set_order),
           .fill = factor(.fill, levels = fill_levels))
  tot <- plot_dat |> group_by(.set) |> summarise(n = sum(n), .groups = "drop")

  ggplot(plot_dat, aes(.set, n, fill = .fill)) +
    geom_col(width = 0.72, show.legend = length(fill_levels) > 1) +
    geom_text(data = tot, aes(.set, n, label = n), inherit.aes = FALSE,
              vjust = -0.45, size = base_size / 3.4, colour = "grey25") +
    scale_fill_manual(values = pal_for(fill_levels, palette), name = fill_title) +
    scale_y_continuous(breaks = int_breaks(5),
                       expand = expansion(mult = c(0, 0.10))) +
    labs(x = set_axis_title, y = bar_axis_title) +
    theme_minimal(base_size = base_size) +
    theme(panel.grid.minor   = element_blank(),
          panel.grid.major.x = element_blank(),
          axis.text.x        = element_text(angle = 35, hjust = 1),
          legend.position    = if (length(fill_levels) > 1) "right" else "none",
          text               = element_text(colour = "grey15"))
}

save_fig <- function(plot, name, width = 9, height = 6) {
  ggsave(file.path(out_dir, paste0(name, ".png")), plot,
         width = width, height = height, dpi = 600, bg = "white")
  ggsave(file.path(out_dir, paste0(name, ".pdf")), plot,
         width = width, height = height, device = cairo_pdf)
  invisible(plot)
}

# =============================================================================
# Figure 2. Studies by sport and study area  (stacked bar - sport is recorded
#           one value per study, so an UpSet matrix would be a diagonal)
# =============================================================================
fig2 <- make_stacked_bar(dat, "Sport", "Area",
                         set_axis_title = "Sport",
                         fill_title     = "Study area")
save_fig(fig2, "Fig2_sport_by_area", width = 7, height = 4.6)

# =============================================================================
# Figure 3. Study context by study area  (all studies)
# =============================================================================
fig3 <- make_upset(dat, "Study Context", "Area",
                   set_axis_title = "Study context",
                   fill_title     = "Study area")
save_fig(fig3, "Fig3_context_by_area", width = 8.5, height = 4.8)

# =============================================================================
# Figure 4. Sport-specific skill  (sport-specific skill studies only)
# =============================================================================
fig4 <- make_stacked_bar(filter(dat, Area == "Sport specific skill"),
                         "Sport Specific Skill", "Area",
                         set_axis_title = "Sport-specific skill",
                         fill_title     = "Study area")
save_fig(fig4, "Fig4_skill", width = 7, height = 4.6)

# =============================================================================
# Figure 5. Assessment methods by assessment technology
#           (sport-specific skill studies only)
# =============================================================================
fig5 <- make_upset(filter(dat, Area == "Sport specific skill"),
                   "Assessment Method", "Assessment Technology",
                   set_axis_title = "Assessment method",
                   fill_title     = "Assessment technology",
                   palette        = "B")          # inferno
save_fig(fig5, "Fig5_method_by_tech_skill", width = 10, height = 5.6)

# =============================================================================
# Figure 6. Collective behaviour  (collective behaviour studies only)
# =============================================================================
fig6 <- make_upset(filter(dat, Area == "Collective behaviour"),
                   "Collective Behaviour", "Area",
                   set_axis_title = "Collective behaviour",
                   fill_title     = "Study area")
save_fig(fig6, "Fig6_behaviour", width = 8, height = 4.6)

# =============================================================================
# Figure 7. Assessment methods by assessment technology
#           (collective behaviour studies only)
# =============================================================================
fig7 <- make_upset(filter(dat, Area == "Collective behaviour"),
                   "Assessment Method", "Assessment Technology",
                   set_axis_title = "Assessment method",
                   fill_title     = "Assessment technology",
                   palette        = "B")          # inferno
save_fig(fig7, "Fig7_method_by_tech_behaviour", width = 10, height = 5.6)

# ---- optional: palette comparison for Figs 5 and 7 --------------------------
# Off by default so only the submitted figures are written. Set to TRUE to
# write Fig 7 in alternative palettes. Swap `palette =` above to any of:
# "D" viridis, "B" inferno, "A" magma, "C" plasma, "E" cividis, "G" mako,
# "F" rocket.
make_palette_previews <- FALSE

if (make_palette_previews) for (opt in c("B", "E", "G")) {
  save_fig(make_upset(filter(dat, Area == "Collective behaviour"),
                      "Assessment Method", "Assessment Technology",
                      set_axis_title = "Assessment method",
                      fill_title     = "Assessment technology",
                      palette        = opt),
           paste0("Fig7_palette_", c(B = "inferno", E = "cividis",
                                     G = "mako")[[opt]]),
           width = 10, height = 5.6)
}

message("Done - figures written to ", normalizePath(out_dir))
